name: Unittest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install required packages
        run: pip install '.[dev]'
      - name: Run pytest with coverage
        run: pytest
